[tool.ruff]
# https://github.com/charliermarsh/ruff/#supported-rules
select = [
    "E",    # pycodestyle
    "W",    # pycodestyle
    "F",    # Pyflakes
    "T10",  # flake8-debugger
    "T20",  # flake8-print
    "Q",    # flake8-quotes
    "C4",   # flake8-comprehensions
    "C90",  # mccabe
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "ERA",  # eradicate
    "RUF",  # ruff-specific rules
]
target-version = "py311"

[tool.ruff.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
    "pydantic.root_validator"
]